import { FC } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import ClientProvider from './provide';

import type { Metadata } from 'next';
import ClientHeaderFooter from './layoutcomponent/ClientHeaderFooter';
import ClientProviderQuery from './lib/ClientProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        <ClientProvider>
        <ClientProviderQuery>
          <ClientHeaderFooter>
            {children}
          </ClientHeaderFooter>
          </ClientProviderQuery>
        </ClientProvider>
      
      </body>
    </html>
  );
};

export default RootLayout;
